[platformio]
default_envs = c3-supermini
src_dir = firmware/src

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio

lib_deps =
  moononournation/GFX Library for Arduino
  olikraus/U8g2
  knolleary/PubSubClient
  bblanchon/ArduinoJson

extra_scripts =
  post:scripts/merge_firmware.py

[env:c3-supermini]
board = esp32-c3-devkitm-1
build_flags =
  -D BOARD_C3_SUPERMINI
  -D ARDUINO_USB_CDC_ON_BOOT=1
custom_chip = esp32c3
custom_boot_offset = 0x0
custom_output = site/firmware/c3-supermini/firmware.bin

[env:s3-devkit]
board = esp32-s3-devkitc-1
build_flags =
  -D BOARD_S3_DEVKIT
  -D ARDUINO_USB_CDC_ON_BOOT=1
custom_chip = esp32s3
custom_boot_offset = 0x0
custom_output = site/firmware/s3-devkit/firmware.bin

[env:esp32-wroom]
board = esp32dev
build_flags =
  -D BOARD_ESP32_WROOM
custom_chip = esp32
custom_boot_offset = 0x1000
custom_output = site/firmware/esp32-wroom/firmware.bin
